spring.profiles.active=default
server.port=9091
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl19c
spring.datasource.username=ecomuserapr26
spring.datasource.password=ecom
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.cloud=DEBUG

logging.level.com.mycomp=DEBUG

logging.file.name=C:\\IntelliJWS\\\MicroServicesApr26\\category\\categoryapp.log

eureka.client.serviceurl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*

category.version=1.2
category.contactname=Charles Keith
category.contactnumber=1234567890
